cloud-hypervisor/rust-hypervisor-firmware

src/fat.rs
Inside the FAT directory entry the 8.3 format filename is stored without
the "." and with padding spaces if the first part is shorter than 8
bytes. Rather than directly comparing the byte slices for the short name
instead match the 8.3 format components separately and thus allow the
user to use a name without padding and with the separator.
FAT filesystem paths are often used with backslashes so accept both
forward and backslashes when traversing the directory.
=> fat: Intelligently compare filename on open()

src/main.rs, src/pci.rs
Rather than only booting from the first block device instead try them all.
Fixes: #16
=> Try and boot from all block devices

src/block.rs, src/efi/block.rs
Add support for writing to virtio-block devices.
=> Implement write support

src/bzimage.rs
We use 2MiB pages so align the start of the address for the initrd to
the page boundary to prevent the kernel trying to access memory outside
of the accessible memory (initrd is placed a the top of usable RAM.)
=> bzimage: Align start of initrd to page boundary

README.md
Find the cmd is broken after following the steps in README.
Signed-off-by: Ning Yang <csyangning@gmail.com>
=> README: fix cmd for run with cloud hypervisor

Jenkinsfile
=> CI: Add coreboot dependencies

src/efi/mod.rs
This PR addresses a vanilla Ubuntu Xenial image boot fail issue by converting RuntimeServices physical addresses to virtual addresses.
As mentioned in issue #53, the current implementation does not handle the `SetVirtualAddressMap` correctly. This causes an unhandled page fault after the `SetVirtualAddressMap` call as RuntimeServices are remapped to the virtual addresses.
```
[    0.079765] BUG: unable to handle kernel paging request at 0000000000124d58
[    0.080549] IP: [<ffffffff8170fa76>] virt_efi_set_variable+0x76/0xc0
```
If we strictly follow the UEFI spec., we have to change the current design(e.g., make the binary relocatable, create ELF loader, etc.). However, almost all the RuntimeServices functions in this firmware are not implemented yet. Instead of implementing relocation, …
=> efi: Fixup RuntimeServices pointers on SetVirtualAddressMap

Cargo.lock, Cargo.toml
=> build: Update dependencies

run_integration_tests.sh
=> build: Update integration tests to use latest CH release

README.md
=> README: Update to reflect current functionality and usage

src/pe.rs
This PR is to address issue #104.
As per the PE format spec, we cannot assume that the sections that
contain specific tables have specific names. The PE loader should find
the base relocation table from the data directory entry in the optional
header.
=> pe: Use data directory entry to find base relocation table

src/efi/mod.rs
The UEFI Spec does not imply when the descriptor_size and
descriptor_version should be updated. However, a recent Linux kernel (at
least v5.8) expects these values are filled even if the memory_map_size
is too small. This assumption causes divided-by-0 exception during the
boot and system reboot. This commit adds null checks and fixes the
behavior. This fix is to address issue #107.
=> efi: Fix get_memory_map to update descriptor info

fetch_disk_images.sh, src/integration.rs
=> tests: Add groovy integration test

Jenkinsfile, fetch_disk_images.sh, run_coreboot_integration_tests.sh, run_integration_tests.sh
This PR addresses issue #112 and reduces disk space to make the tests quicker and more efficient.
=> CI: Improve integration tests

src/integration.rs
This commit changes integration tests to show output on fail only. The
test thread stdout and stderr are redirected to tempfiles and the child
handler handles the output. The most of the code comes from Cloud
Hypervisor integration test code.
=> tests: Improve integration tests output format

.github/workflows/build.yaml, .github/workflows/release.yaml, run_integration_tests.sh
=> tests: Update to latest version of Cloud Hypervisor

fetch_disk_images.sh
=> scripts: Use CDN to download Clear image

src/fat.rs
One byte out-of-bounds read happens if the offset is 511 in
next_cluster(). This causes the boot fail issue reported in #132.
=> fat: Fix out-of-bounds read in next_cluster

run_integration_tests.sh
=> tests: Update tests to CH v17.0

run_integration_tests.sh
=> build: Update CH version used in CH tests to latest release

scripts/run_integration_tests.sh, scripts/run_integration_tests_windows.sh
=> build: Bump Cloud Hypervisor version used for CI to v20.0

src/efi/file.rs, src/fat.rs
Current implementation checks if the buffer has enough length after the directory entry moves next. and it doesn't rewind the directory entry.
This may cause an EFI application to miss some directory entries.
This commit changes checking the buffer length first.
Thanks to it, the directory entry doesn't move next and doesn't need to be rewinded even if the buffer is too small.
It also adds checking if the directory entry is last one because read() must not return BUFFER_TOO_SMALL in this case.
Fixes:#166
Signed-off-by: Yuji Hagiwara <yuuzi41@gmail.com>
=> efi: Check if the buffer has enough length in read() of a directory first

scripts/run_integration_tests.sh
=> scripts: Update version of CH tests to v22.1

src/bzimage.rs
Simplified checks for address/size out of range but also a new check to
limit to identity mapped 4GiB region.
The potential address is now clamped to the max start address if that is
in the range. This fixes the issue with booting with more than 2GiB as
the Linux max is just under 2GiB and previously the potential address
would be at the top of the 3GiB boundary when running with more than
2GiB.
Tested with image boot with initrd with 1GiB and 4GiB RAM.
Fixes: #175
=> bzimage: Improve initrd memory allocation

scripts/run_integration_tests.sh
=> scripts: Bump Cloud Hypervisor version in integration test

Cargo.lock, Cargo.toml
=> build: Bump version for 0.4.0 release

src/fat.rs
According to Microsoft FAT32 File System Specification [1], a FAT file
system driver should first determine the count of sectors used by the
root directory to determine the FAT type. This commit improves the
compatibility of the initialization process as described in the spec.
[1]
https://download.microsoft.com/download/1/6/1/161ba512-40e2-4cc9-843a-923143f3456c/fatgen103.doc
=> fat: Improve FAT type determination compatibility

src/pe.rs
This commit replaces the hard-coded magic numbers in the PE parser with configurable constant values. This change makes supporting other architectures easier in the future.
=> pe: Replace hard-coded magic numbers in PE parser

Cargo.lock, Cargo.toml, src/efi/mod.rs
This commit also fixes build issues with the update.
=> build: Bump r-efi from 4.0.0 to 4.1.0

src/block.rs
TEST=Boot cloud-hypervisor with read-only block device and observe that
writes generate errors in the EFI/boot loader code but the OS continues
to boot.
Fixes: #209
=> block: Error out on write/flush if device is read-only

Cargo.lock, Cargo.toml
=> build: Bump version for 0.4.2 release

rust-toolchain.toml, src/fat.rs, src/integration.rs, src/loader.rs, src/main.rs, src/part.rs, src/pci.rs
This PR updates the Rust toolchain and adds suggested changes from Clippy.
=> build: Update Rust toolchain to 2023-02-10-nightly

scripts/fetch_images.sh, src/integration.rs
=> scripts: Bump version of CH used

README.md
=> Systemd related content has moved to UAPI website

riscv64gcv-unknown-none-elf.json, rust-toolchain.toml, src/arch/aarch64/paging.rs, src/arch/x86_64/paging.rs, src/boot.rs, src/bzimage.rs, src/common.rs, src/efi/alloc.rs, src/efi/block.rs, src/efi/mod.rs, src/fat.rs, src/integration.rs, src/layout.rs, src/loader.rs, src/main.rs, src/mem.rs, src/part.rs, src/virtio.rs, x86_64-unknown-none.json
This PR updates the Rust toolchain to nightly-2024-05-13 with fixing several build errors/warnings.
=> build: Update toolchain to nightly-2024-05-13

Cargo.lock, Cargo.toml
=> build: Bump version for 0.5.0 release

src/arch/aarch64/paging.rs, src/arch/x86_64/paging.rs
This PR removes use of unnecessary static mut refs especially in arch-specific paging implementation.
=> arch: Remove use of static mut refs
