- .travis.yml
- rust-toolchain
Current nightly is failing with the CI due to lack of clippy so fix on
the 2019-05-10 version.
> build: Target specific nightly Rust version

- src/main.rs
- src/mem.rs
Sure, why not?
I resisted the urge to change all of the offsets from `u64` to `usize`, which is the natural pointer size of the target, but in my experience on embedded platforms, that's the more idiomatic type to use.
> Generic IO methods

- layout.ld
- target.json
When building for a custom or bare metal platform, it is often be more
useful to use the LLVM linker shipped with Rust (`rust-lld`). As Rust is
heavily integrated with LLVM, using LLVM's linker can result in smaller
and simpler binaries.
This change does two things,
- Changes the linker script (`layout.ld`) to:
- Correctly combine sections together
- Remove `BLOCK` as it does the same thing as `ALIGN`. See:
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/4/html/Using_ld_the_GNU_Linker/expressions.html
- Changes `target.json` to use `rust-lld`
The results:
- The debug build now works!!
- The release binary is now smaller and simpler
- Size shrinks from 116 KB to 70 KB
- Stripped size shinks from 89 KB to 49 KB
- Number of sections shinks from 333 to 10
- Program …
> Linker: Change to rust-lld for linking

- src/fat.rs
Locate the next cluster when sector within the cluster (self.sector) is
greater than or equal to the number of sectors in the cluster. This is
needed as the sector is zero indexed and the increment happens on a
previous loop around.
> fat: Fix directory handling that spans multiple clusters

- src/efi/mod.rs
To allow EFI booted systems to shutdown and reboot.
> Expose ACPI tables via EFI

- src/block.rs
Currently the only feature supported is the standard virtio v1 feature.
> block: Only negotiate the virtio features that we support

- .cargo/config
- .travis.yml
- Cargo.toml
- layout.ld
- target.json
This change is a few small fixes to `target.json` and `layout.ld`
- Set stripping in `layout.ld`
- Fixes my mistake from #20 
- We already set linking flags in `layout.ld`, we shouldn't also be setting them in a second place.
- I updated the comments to explain why we can also do this for `panic = "abort"`
- Without setting the default target to be `target.json`, `cargo check` and `cargo clippy` will break when building for the host target.
- Merge `.bss` into `.data`
- This [`.bss` section](https://en.wikipedia.org/wiki/.bss) normally represents "uninitialized/zero" data that will later be written by the program. Generally this means it has a runtime memory area, but no corresponding data in the output binary. The program header just says where to load it.
- To make the loader's job …
> build: improve linker script and target settings

- Cargo.lock
- Cargo.toml
- layout.ld
- src/asm/ram64.s
- src/block.rs
- src/bzimage.rs
- src/common.rs
- src/efi/alloc.rs
- src/efi/block.rs
- src/efi/console.rs
- src/efi/file.rs
- src/efi/mod.rs
- src/loader.rs
- src/logger.rs
- src/main.rs
- src/mmio.rs
- src/pci.rs
- src/virtio.rs
Depends on #23 
We only use `lazy_static` for `spin::Mutex`, but that has a `const fn` constructor, so `lazy_static` isn't needed. See the individual commits for more detailed info.
The only significant change was adding a `const fn` implementation for `Allocator::new`, as `Default::default` is never `const fn`.
Binary sizes (release build, in bytes, log-serial = true, log-panic = false):
```
Before #23:    58848
After #23:     58600
This PR + #23: 40264 (down to 31656 with no logging)
```
> Remove `lazy_static` dependancy

- src/efi/console.rs
- src/serial.rs
The current serial implementation will panic if you log! within a log!
statement. For example, the following code panics:
```rust
fn foo() {
log!("foo: {}", bar());
}
fn bar() -> u64 {
log!("bar");
42
}
```
We change the implementation to have the `PORT` be static rather than
the entire `Serial` structure.
> serial: Fix bug with nested logging

- layout.ld
- src/asm/gdt64.s
- src/asm/mod.rs
- src/asm/note.s
- src/asm/ram32.s
- src/asm/ram64.s
- src/boot.rs
- src/bzimage.rs
- src/common.rs
- src/efi/mod.rs
- src/fat.rs
- src/loader.rs
- src/main.rs
- src/mem.rs
- src/paging.rs
- src/pe.rs
- src/pvh.rs
- src/virtio.rs
Fixes #6 
This PR adds support for booting via the [Xen HVM direct boot ABI](https://xenbits.xen.org/docs/4.12-testing/misc/pvh.html) otherwise known as the PVH Boot Protocol.
This required significant cleanup to how we load the Linux Kernel, as the existing code wasn't doing the exact correct thing. All of the commits that _don't_ start with `pvh:` are part of this cleanup. The commits that _do_ start with `pvh:` specifically address adding PVH support (including the transition for 32-bit to 64-bit mode).
This allows our firmware to be used with QEMU's `-kernel` option. This can be invoked like:
```
qemu-system-x86_64
-machine type=q35,accel=kvm \
-cpu host \
-smp 1 \
-m 1024 \
-display none \
-serial stdio \
-kernel target/target/release/hypervisor-fw \
-drive …
```
> pvh: Support booting via PVH ELFNOTE

- src/block.rs
- src/main.rs
There is no need to reset the device as Cloud Hypervisor supports device
reset itself (so the booted kernel will correctly reset the device on
boot.)
In particular resetting the block device prior to booting via EFI breaks
the EFI boot.
Fixes: #35
> main, block: Remove device.reset()

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/serial.rs
When trying to run this on various hypervisors (QEMU, GCE, etc...), I
noticed that our serial implementation is not very robust.  We can
start in the wrong mode or drop bytes, as we do not properly observe
the status bits or setup the configuration registers.
Instead of doing this ourselevs, we just use an external crate. Note
that this create is made by the same people as x86_64, and only has
that crate as a dependancy.
Signed-off-by: Joe Richey <joerichey@google.com>
> serial: Use external uart_16550 crate

- .travis.yml
- Cargo.toml
- README.md
- run_integration_tests.sh
- src/asm/ram32.s
- target.json
Fixes #67 
For details about the changes, see each step.
Note that the only major difference from `cargo-xbuild` is that:
- This doesn't require and external tool
- When not using `--release`, `libcore` and `compiler-builtins` are built in debug mode
- This means we cannot enable LTO with debug mode anymore (but that's OK).
> Use -Zbuild-std

- src/fat.rs
This is undefined behaviour:
https://github.com/rust-lang/rust/issues/46043
Fixes: #70
> fat: Don't reference packed fields

- src/main.rs
- src/pe.rs
This PR improves PE relocation support.
4c2696a and 10ef5a7 are small fixes based on the PE/COFF format specification. 4c2696a fixes the panic reported in issue #73.
794caf6 changes the loader behavior to load to the preferred address if the ImageBase in the PE header is a non-zero value.
If it is not specified, it loads at the binary at the default address `0x20_0000`.
> pe: Improve PE Loader Relocation

- .travis.yml
- Cargo.lock
- Cargo.toml
- README.md
- run_coreboot_integration_tests.sh
- run_integration_tests.sh
- src/efi/mod.rs
- src/efi/var.rs
- src/main.rs
Some vanilla Ubuntu (Bionic and Focal) boot images fail to boot because EFI variables are not supported, as mentioned in issue #77.
This PR proposes simple EFI variable support for this problem. The `VariableAllocator` provides `SetVariable ()` and `GetVariable ()` before `ExitBootServices ()` called. The EFI variables are stored in the memory and volatile after reboots even if `EFI_VARIABLE_NON_VOLATILE` is specified.
It also adds a global allocator to make heap-allocated data structures available. Since this firmware already has a page-level allocator for EFI, the heap allocator manages the only fixed size of memory given from the page allocator.
Currently, the heap is used only for the EFI variable allocator, but it may be useful for implementing other features.
However, the boot …
> efi: Add GlobalAlloc and EFI Variable Support

- src/common.rs
- src/efi/file.rs
- src/fat.rs
- src/loader.rs
This PR mainly proposes two features:
1. 3449aa1: Add open from non-root directory support
2. c43e59d: Add directory read support
Some bootloaders (e.g., `fbx64.efi` from shim) need these features to traverse the given filesystem. The rough design is based on the discussion in issue #19, which introduces `Node` enum to abstract `Directory` and `File`.
It also includes some small fixes for EFI compatibility.
Once this PR is merged, issue #19 can be closed.
> efi: Improve Directory Open/Read

- fetch_disk_images.sh
- src/efi/alloc.rs
- src/efi/file.rs
- src/efi/mod.rs
- src/fat.rs
- src/integration.rs
This PR proposes changes to support unmodified Ubuntu image boot.
The main changes are implementing load_image (9fd3a8b) and start_image (ae7f47b) to load/start the second-stage bootloader.
I tested with:
* [Ubuntu 18.04 LTS [20210319]](https://cloud-images.ubuntu.com/bionic/20210319): bionic-server-cloudimg-amd64.img
* [Ubuntu 20.04 LTS [20210316]](https://cloud-images.ubuntu.com/focal/20210316): focal-server-cloudimg-amd64.img
Boot Flow: BOOTX64.EFI (shimx64.efi) -> fbx64.efi -> shim64.efi -> grubx64.efi -> Linux kernel.
> Add support off-the-shelf Ubuntu image boot

- Cargo.toml
- layout.ld
- src/asm/ram32.s
- src/delay.rs
- src/efi/mod.rs
- src/gdt.rs
- src/main.rs
- src/rtc.rs
This is the subset of patches from #110 without the integration tests for Windows. I would like to merge these and then make a new release here and use that in CH's upcoming release. However the Windows integration tests here need a fix that is not yet in a released CH.
> Improved EFI support towards Windows guest

- src/rtc.rs
c12cadd fixes RTC value format checks if it needs BCD to decimal conversion. This bug causes Windows 10 20H2 boot to fail on the bootmgfw.efi 1st stage bootloader. (Note that 2c9ca2f4621e0c2e0ddb467067828783524f2c72 still makes boot fail on runtime phase.)
8066695 is not to read RTC register B value every time.
> rtc: Fix BCD to decimal conversion checks

- Cargo.toml
- Jenkinsfile
- run_coreboot_integration_tests.sh
- run_integration_tests.sh
- src/efi/mod.rs
- src/integration.rs
- target.json
The changes in this PR are to support Windows guests. I previously added EFI variable feature to support stock Ubuntu images, but it seems to be needed to boot Linux and blocks Windows boot. So let's opt out the feature.
> efi: Improve Windows Guest Support

- Cargo.lock
- Cargo.toml
- Jenkinsfile
- run_integration_tests.sh
- src/efi/alloc.rs
- src/efi/block.rs
- src/efi/file.rs
- src/efi/mod.rs
- src/integration.rs
All enums are converted to constants from 4.0.0. This commit is to follow
this backward compatibility breaking change.
> build: Bump r-efi from 3.2.0 to 4.0.0

- src/pci.rs
Current implementation only probes to the fifth BAR (0x20).
FWIW this PR allows to probe the sixth BAR.
> pci: Probe sixth BAR as well

- src/asm/mod.rs
As reported in issue #143, recent nightly rustc fails to compile the
assembly file because it uses AT&T syntax. It is also suggested that use
raw option when using `include_str!` macro.
https://rust-lang.github.io/rfcs/2873-inline-asm.html#options-1
https://github.com/rust-lang/rust/pull/86599
> asm: Add att_syntax and raw options

- src/main.rs
main: Remove redundant constructor call in main function
In the `main` function in `main.rs`, there was an unintended call to the
constructor of `VirtioBlockDevice` following the definition of
`pci_transport`. This PR removes that unused call.
Signed-off-by: henryksloan@gmail.com
> Remove redundant constructor call in main function

- src/fat.rs
- src/loader.rs
compare_name function and compare_short_name function compare incompletely if the argument "name" is shorter than a name of directory entries.
This causes a failure to load EFI as reported in #164
Signed-off-by: Yuji Hagiwara <yuuzi41@gmail.com>
> fat: Fix incomplete comparing in compare_name and compare_short_name

- scripts/fetch_disk_images.sh
- src/integration.rs
Ubuntu 21.04 Hirsute Hippo reached the EOL on January 20, 2022. This
commit updates to Ubuntu 22.04 Jammy Jellyfish.
Fixes #168 CI error.
> tests: Replace Ubuntu Hirsute with Jammy

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- Cargo.toml
- resources/Dockerfile
- rust-toolchain.toml
- src/block.rs
- src/efi/mod.rs
- src/fat.rs
- src/rtc.rs
- src/serial.rs
This PR proposes updating the Rust toolchain to nightly-2022-06-10. It also fixes some issues newly reported by clippy.
> build: Update toolchain to nightly-2022-06-10

- Cargo.lock
- Cargo.toml
- src/efi/mod.rs
This commit also fixes a build error.
> build: Bump linked_list_allocator from 0.9.1 to 0.10.0

- src/fat.rs
- src/loader.rs
- src/main.rs
Resolves #183
This update implements matching of boot entry names against the pattern in the
`default` option from `loader/loader.conf`, intended to be compatible with the
behaviour of `systemd-boot`.
> Handle `default` bootloader entry patterns correctly

- src/block.rs
- src/bzimage.rs
- src/efi/block.rs
- src/efi/file.rs
- src/fat.rs
- src/loader.rs
- src/part.rs
- src/pe.rs
This PR proposes improving block device portability by reducing hard-coded sector size.
The current implementation assumes that a sector size is always 512 bytes. This can be a blocking issue when supporting block devices with other sector sizes. To improve the code portability, 4b44f79c0e48cc2519cd02f12d2058c0302b56e4 introduces `SectorBuf` that represents a single sector buffer instead of `[u8; 512]`.
5c1d9429bd98227ff9c3471141677a5a4df62ce8 improves the `VirtioBlockDevice::request()` error handling.
> block: Improve block device portability by reducing hard-coded sector size

- .github/workflows/build.yaml
- .github/workflows/docker-image.yaml
- .github/workflows/release.yaml
- resources/Dockerfile
- scripts/dev_cli.sh
This PR proposes simplifying Rust toolchain selection on GitHub Actions. The current CI config specifies the same toolchain version in multiple locations. This PR changes to use toolchain version defined in rust-toolchain.toml on every CI build.
> build: Use Rust toolchain specified in rust-toolchain.toml

- scripts/make-test-disks.sh
- src/fat.rs
The current implementation is lacking the support for FAT with clusters made of more than one sector. This is fixed by having the internal offset being rounded modulo the size of the list of directories (16) along with updating the current sector.
But this also requires a second patch for operating `Seek` correctly. The sector can't always be reset to 0 (like we do with the offset), which is why an additional field storing the proper value is added to the Directory structure. This allows for a proper reset of the sector related to the directory.
Fixes #199
> fat: Support clusters with multiple sectors

- Cargo.toml
- src/efi/block.rs
- src/efi/console.rs
- src/efi/file.rs
- src/efi/mod.rs
- src/main.rs
This PR improves EFI compatibility to support Linux boot in upcoming aarch64 support tracked in issue #198.
> efi: Improve EFI Compatibility

- src/arch/x86_64/layout.rs
- src/arch/x86_64/mod.rs
- src/arch/x86_64/ram32.s
- src/efi/mod.rs
- src/layout.rs
- src/main.rs
- x86_64-unknown-none.ld
This commit introduces base `layout` mod and x86_64 specific `layout` mod to provide architecture-independent memory mapping info for EFI compatible layer.
> layout: Introduce `layout` for memory mapping

- rust-toolchain.toml
- src/efi/alloc.rs
- src/efi/block.rs
- src/efi/mod.rs
- src/efi/var.rs
- src/fat.rs
- src/integration.rs
- src/pci.rs
This PR proposes updating Rust toolchain to nightly-2022-11-12. It also includes some fixes suggested by the new version of clippy.
> build: Update toolchain to nightly-2022-11-12

- src/boot.rs
- src/bootinfo.rs
- src/bzimage.rs
- src/coreboot.rs
- src/efi/mod.rs
- src/loader.rs
- src/main.rs
- src/pvh.rs
`E820Entry` is used in `boot::Info` trait, which is x86_64-dependent memory entry data structure. It's confusing if e820 is used in other architectures. This commit introduces an architecture-independent memory entry `bootinfo::MemoryEntry` and replaces `boot::Info` with `bootinfo::Info`. This change is suggested in [1].
[1]
https://github.com/cloud-hypervisor/rust-hypervisor-firmware/pull/205#discussion_r1028921329
> bootinfo: Add architecture-independent memory entry

- .github/workflows/build.yaml
- .github/workflows/docker-image.yaml
- Cargo.lock
- Cargo.toml
- Jenkinsfile
- aarch64-unknown-none.json
- aarch64-unknown-none.ld
- build.rs
- resources/Dockerfile
- rust-toolchain.toml
- scripts/dev_cli.sh
- scripts/run_cargo_tests.sh
- src/arch/aarch64/asm.rs
- src/arch/aarch64/layout.rs
- src/arch/aarch64/mod.rs
- src/arch/aarch64/paging.rs
- src/arch/aarch64/ram64.s
- src/arch/aarch64/translation.rs
- src/arch/mod.rs
- src/delay.rs
- src/efi/mod.rs
- src/fdt.rs
- src/main.rs
- src/pci.rs
- src/pe.rs
- src/rtc.rs
- src/rtc_pl031.rs
- src/serial.rs
- src/uart_pl011.rs
This PR proposes introducing an initial aarch64 support (#198) for aarch64/KVM Cloud Hypervisor.
~~NOTE: This is a draft PR. It is not ready for review. The main blocking issue is that the changes in commit a2a986f92917b2ed5851e3e703236f8eb8ed490d leads to fail existing CI tests. I need to fix the breaking changes.~~
> arch: Add aarch64 support

- Cargo.lock
- Cargo.toml
- src/arch/aarch64/mod.rs
- src/arch/aarch64/paging.rs
- src/arch/aarch64/simd.rs
- src/main.rs
These changes are required to run a recently built GRUB binary as described in the commit 89764cf4fa2498a5d08de4ec660d52c44dd39c73.
> aarch64: Setup SIMD at startup

- scripts/fetch_images.sh
- src/integration.rs
As Cloud Hypervisor v30.0 has been released, this PR bumps the target version to the latest.
NOTE: This PR should be merged after PR #219 is merged.
> scripts: Bump Cloud Hypervisor version to v30.0

- src/pci.rs
- pci: Adjust conditional compilation rules
- pci: Make x86-64 I/O port Read/Write
- pci: Add support for writing to PCI config space
- pci: Probe and report out PCI BAR sizes
> Discover PCI BAR sizes

- src/efi/mod.rs
- src/main.rs
Since the EFI ABI expects `\\` as the directory separator and our FAT
implementation accepts both then use that as the preferred version.
> efi: Use a constant for the EFI boot path

- src/arch/x86_64/layout.rs
- src/bootinfo.rs
- src/bzimage.rs
- src/coreboot.rs
- src/efi/mod.rs
- src/fdt.rs
- src/loader.rs
- src/main.rs
- src/pvh.rs
- bootinfo: Use Option<u64> for address of RSDP
- coreboot: Make module inclusion architecture specific
- fdt: Make available the guest FDT table if necessary
- bootinfo: Reduce hardcoding of load address for kernel
- bootinfo: Include reference to memory layout
> Increase portability though existing Info trait

- src/bootinfo.rs
- src/fdt.rs
- src/main.rs
- src/pci.rs
- bootinfo: Support specifying a region to allocate PCI BARs from
- pci: Allocate PCI BARs from advertised range
- fdt: Support adjusting Info::pci_bar_memory()
> Allocate PCI BARs where needed

- src/efi/mod.rs
Populate with FDT if available, ACPI if available and falling back to the
zero vendor data if neither are available.
> efi: Populate EFI configuration table as much as possible

- src/pci.rs
Specifying the address in PCI ECAM space is different than in PCI I/O
config space.
> pci: Use correct address calculation for PCI ECAM

- .github/workflows/docker-image.yaml
- resources/Dockerfile
- scripts/dev_cli.sh
The small team DockerHub account is going away so the logical place to
store the built container is in the GitHub container registry.
> build: Store container in ghcr vs DockerHub

- Jenkinsfile
- scripts/dev_cli.sh
- src/efi/mod.rs
Here are some fixes I needed to make for enabling booting Linux using the EFI
Stub support.
- efi: Include a firmware vendor string
- efi: Populate CopyMem/SetMem EFI functions
- efi: Make the heap size more reasonable
> Linux EFI Stub fixes

- src/pci.rs
Rust Hypervisor Firmware panics on the overflow with debug build on x86_64.
This PR proposes:
* 7ff9dea1064d09b52cebc2ab0d3f7acb1a454e22: Fix typo
* 62558d16ee4f35a06dd7bdf947655761590aad0d: Handle overflow on 32-bit PCI BAR size calculation
> pci: Handle overflow on 32-bit PCI BAR calculation

- .github/workflows/build.yaml
- Cargo.toml
- README.md
- riscv64gcv-unknown-none-elf.json
- riscv64gcv-unknown-none-elf.ld
- src/arch/mod.rs
- src/arch/riscv64/asm.rs
- src/arch/riscv64/layout.rs
- src/arch/riscv64/mod.rs
- src/arch/riscv64/ram64.s
- src/bootinfo.rs
- src/delay.rs
- src/efi/mod.rs
- src/fdt.rs
- src/main.rs
- src/pe.rs
- src/rtc.rs
- src/rtc_goldfish.rs
- src/serial.rs
- src/uart_mmio.rs
Add support for running under RISC-V QEMU emulation using virt machine type
loaded from OpenSBI.
- efi, fdt: Mark the size of the FDT table as reserved
- build: Use fork of r-efi with riscv64 support
- rtc: riscv: Add RTC support via goldfish RTC
- delay: riscv: Add implementation of ndelay()
- efi: riscv: Add EFI default boot path for the RV64 target
- pe: riscv: Enable PE32+ loader support
- efi: riscv: Add platform specific EFI Boot Protocol implementation
- serial: riscv: Add basic MMIO UART device
- misc: riscv: Add support for starting on QEMU virt machine
- README: riscv: Add documentation for new platform
- build: riscv64: Add cross toolchain build testing
> Add RISC-V support

- README.md
I tested this on my x86-64 laptop, and it built without any problem. Later I will try the output to see if it runs with cloud-hypervisor to possibly add a "running" section, but I have to arrange the correct server first.
> Add AArch64 build section

- scripts/dev_cli.sh
Current local variable `exported_device` under `cmd_build()` misses the root directory in the beginning, which will lead to the error of:
```
docker: Error response from daemon: OCI runtime create failed:
invalid mount {Destination:dev/kvm Type:bind
[...]
Options:[rbind]}: mount destination dev/kvm not absolute: unknown.
```
when running `scripts/dev_cli.sh build` command.
Fix the path by following the `cmd_test()`.
> dev_cli.sh: Fix kvm directory path of the build command

- aarch64-unknown-none.ld
- src/arch/aarch64/layout.rs
- src/arch/aarch64/paging.rs
- src/arch/aarch64/translation.rs
- src/main.rs
There are some issues for rust firmware on arm64:
Two of them:
- use atomic instruction before mmu enabled may cause exception;
- page table creation takes too long;
To address above issues:
- Use atomic operation after MMU enabled;
- optimize page table creation algorithem;
> AArch64: speed up paging and fix exception caused by atomic operation

- resources/Dockerfile
- rust-toolchain.toml
- scripts/fetch_images.sh
- src/block.rs
- src/efi/alloc.rs
- src/efi/mod.rs
- src/integration.rs
This PR proposes updating Rust toolchains and integration tests. It also removes Ubuntu 18.04 TLS Bionic from the integration test targets as it will reach its EOL this month.
> build: Update toolchain and tests

- src/uart_pl011.rs
In current implementation of pl011, LF is just as LF. It is not the rule in Unix-like world which treats LF as CRLF.
See related linux kernel doc [1]
[1] https://www.kernel.org/doc/Documentation/serial/driver
Fixes: #258
> Serial/AArch64: treat LF as LF + CR

- src/arch/x86_64/asm.rs
- src/arch/x86_64/gdt.rs
- src/arch/x86_64/paging.rs
- src/arch/x86_64/ram32.s
- src/arch/x86_64/sse.rs
- src/block.rs
- src/bzimage.rs
- src/common.rs
- src/efi/alloc.rs
- src/efi/block.rs
- src/efi/console.rs
- src/efi/file.rs
- src/efi/mod.rs
- src/fat.rs
- src/integration.rs
- src/loader.rs
- src/main.rs
- src/mem.rs
- src/part.rs
- src/pci.rs
- src/pe.rs
- src/pvh.rs
- src/serial.rs
- src/virtio.rs
This PR proposes:
* Replace Apache license texts with SPDX license identifiers.
* Add missing license and copyright notices.
Some of the code files originally written by @josephlr do not have copyright notices. I'd like to confirm this with him, as I'm not sure if these contributions were made as Google or individually.
> misc: Clean up license notices and copyrights

- aarch64-unknown-none.ld
- src/arch/aarch64/ram64.s
- src/efi/alloc.rs
- src/efi/mod.rs
- src/fat.rs
- src/main.rs
There are several issues block ubuntu 20.04+ boot from rust hypervisor firmware:
1. Grub or UEFI Shim may large enough and overlaps the firmware code region;
2. UEFI Shim or Grub file name length longer than 11 can't be expressed correctly: for example: "BOOTAA64.CSV" will be carried as "BOOTAA64CSV" in rust hypervisor firmware;
3. EFI memory allocations can be ran out;
4. Pass full fdt to OS blocks ACPI initialization;
This PR try to fix them one by one:
1. Move code start address upward to enlarge the memory region used for loading Grub/Shim;
2. Fixup fat file name if needed;
3. Bump allocations max number;
4. Don't pass fdt in system configuration table;
After above fix, ubuntu 20.04+ can boot from rust hypervisor firmware. Test pass for ubuntu 18.04, 20.04 and 22.04.
Fixes: #261
> AArch64: let ubuntu 20.04+ boot from rust hypervisor firmware

- Cargo.lock
- Cargo.toml
- src/efi/mod.rs
- src/main.rs
The PR https://github.com/cloud-hypervisor/rust-hypervisor-firmware/pull/264 Clippy CI check is failing due to the conflicts with dependency crates. This PR includes a fix commit.
> build: Bump tempfile from 3.6.0 to 3.7.0

- Jenkinsfile
- scripts/dev_cli.sh
- scripts/fetch_images.sh
- scripts/run_coreboot_integration_tests.sh
- scripts/run_integration_tests.sh
- scripts/run_integration_tests_windows.sh
- src/integration.rs
Since PR #262 was merged, we can boot Ubuntu images using aarch64 Cloud Hypervisor. This PR proposes adding integration tests for aarch64 CH.
> tests: Add integration tests for aarch64

- rust-toolchain.toml
- scripts/fetch_images.sh
- src/boot.rs
- src/efi/mod.rs
- src/efi/var.rs
- src/integration.rs
- src/main.rs
- src/mem.rs
- src/pe.rs
This PR proposes updating Rust toolchain to nightly-2023-08-11. With this update, we need to change some of the code as suggested by clippy. It also includes fix potential unaligned access in PE loader.
> build: Update toolchain to nightly-2023-08-11

- Cargo.lock
- src/rtc_goldfish.rs
- src/rtc_pl031.rs
This PR proposes updating chrono to 0.4.28 and remove use of deprecated functions.
> build: Bump chrono from 0.4.26 to 0.4.28

- Cargo.lock
- Cargo.toml
- src/arch/aarch64/paging.rs
- src/arch/aarch64/simd.rs
This PR fixes build error seen in PR #282.
> build: Bump tock-registers from 0.8.1 to 0.9.0

- src/arch/aarch64/layout.rs
- src/efi/mod.rs
- src/layout.rs
As reported in issue #289, there was an allocation issue with the MMIO region for AArch64 in the EFI layer. This was initially addressed by PR #290, thanks to @jongwu. However, the solution appeared to be somewhat ad-hoc, raising same concerns with the RL011 UART MMIO region.
This PR adds `MemoryAttribute::Mmio` and an MMIO memory descriptor for AArch64 memory layout.
> layout: Add MMIO memory attribute

- .github/workflows/release.yaml
It seems that the https://github.com/cloud-hypervisor/rust-hypervisor-firmware/issues/198 is almost done, so it would be nice if people could download and test the firmware on their arm64 machines instead of building it themselves.
> build: Add aarch64 to release workflow

- scripts/fetch_images.sh
This avoids an issue with CH and a virtio-net bug in the kernel that
prevents it booting.
See: cloud-hypervisor/cloud-hypervisor#5998
> scripts: Use older jammy image

- build.rs
- riscv64gcv-unknown-none-elf.json
As reported in issue https://github.com/cloud-hypervisor/rust-hypervisor-firmware/issues/299, the latest RHF goes boot loop since `nightly-2023-06-07` Rust toolchain. This is because the recent Rust generates code that includes F and V extensions, which we need to enable these features on startup. This commit disables generation of these extensions as a workaround.
Fixes #299.
> riscv64: Avoid F and V instruction generation

- scripts/fetch_images.sh
This PR proposes adding a workaround same as https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6010.
> scripts: Retry Cloud Hypervisor binary download

- src/pci.rs
As per virtio spec 4.1.3.1 [1]:
> For device configuration access, the driver MUST use 8-bit wide
> accesses for 8-bit wide fields, 16-bit wide and aligned accesses for
> 16-bit wide fields and 32-bit wide and aligned accesses for 32-bit
> and 64-bit wide fields.
This patch makes the virtio-pci driver sets 64-bit addresses with 2 32-bit writes to align with the spec.
[1] https://docs.oasis-open.org/virtio/virtio/v1.2/csd01/virtio-v1.2-csd01.html#x1-1220001
> virtio-pci: use 2 32-bit writes for 64-bit fields

- src/efi/file.rs
- src/efi/mod.rs
- efi: Refactor device path protocol parsing
- efi: Refactor construction of file based device path
- efi: Refactor EFI device path generatation for loaded image
- efi: Use DevicePath::generate() for executing the main EFI binary
- efi: Consistently support filenames up to 256 characters
- efi: Move FileDevicePathProtocol struct to where it is used
- efi: Clarify naming of type for two FileDevicePathProtocol
- efi: Add support for memory mapped device path
- efi: Add support for booting from a memory mapped device path
- efi: Refactor code for loading image
GRUB on (at least RISC-V) loads the guest kernel directly into memory and then
expects the firmware to parse it from there - it does this by using a device
path of type PCI and subtype memory mapped.
With this change the Linux kernel …
> Boot from memory device path

- .github/workflows/tests.yaml
- Jenkinsfile
- scripts/run_coreboot_integration_tests.sh
- scripts/run_integration_tests.sh
Migrate the basic x86-64 integration tests to run on GitHub actions.
- scripts: Run integration tests in series
- ci: Run unit & integration tests on GitHub runner
- ci: Remove x86-64 Linux tests from Jenkinsfile
> ci: Migrate some integration tests to GitHub actions

- .github/workflows/build.yaml
- .github/workflows/docker-image.yaml
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- Jenkinsfile
It looks like we have a self-hosted arm64/linux GitHub Actions runner (https://github.com/cloud-hypervisor/cloud-hypervisor/pull/6221).
> ci: Switch arm64 tests to self-hosted GitHub Actions runner

- .github/workflows/dco.yaml
It looks like the DCO bot is not working. We should replace the bot with the GHA workflow imported from Cloud Hypervisor.
> ci: Import DCO check GHA from CH

- .github/workflows/docker-image.yaml
The GitHub Actions that publishes a container image for RHF is failing in recent commit: https://github.com/cloud-hypervisor/rust-hypervisor-firmware/actions/runs/8188441628/job/22392941449. It seems to be some of used actions are old, and the action does not have enough permission to write GitHub packages.
> ci: Update Docker Image Publish CI

- .github/workflows/docker-image.yaml
- rust-toolchain.toml
This update is to trigger container image build.
The [previous CI build](https://github.com/cloud-hypervisor/rust-hypervisor-firmware/actions/runs/8188441628/job/22478383773) is failing due to 403 error: https://github.com/cloud-hypervisor/rust-hypervisor-firmware/actions/runs/8188441628/job/22478383773#step:8:4457.
> build: Update toolchain to nightly-2023-11-11

- scripts/fetch_images.sh
- src/integration.rs
Since the custom Clear Linux image is no longer available, this commit switches to use the upstream image for integration tests.
> integration: Switch to use upstream Clear Linux image

- .github/workflows/build.yaml
- .github/workflows/release.yaml
- Cargo.lock
- Cargo.toml
- README.md
- scripts/dev_cli.sh
- scripts/run_cargo_tests.sh
- scripts/run_coreboot_integration_tests.sh
- scripts/run_integration_tests.sh
- scripts/run_integration_tests_windows.sh
- src/efi/mod.rs
- src/efi/var.rs
PR #92 introduced heap allocator to implement EFI variable feature. However, none of other components uses heap. This commit removes the heap allocator and use the `heapless` crate instead of `Vec`. This change simplifies the build arguments.
> build: Remove heap allocator

- Cargo.lock
- Cargo.toml
- src/arch/x86_64/paging.rs
- src/efi/device_path.rs
- src/efi/file.rs
- src/logger.rs
- src/main.rs
- src/pci.rs
RHF has a simple `log!()` macro with a serial backend for logging, but it lacks a logging level feature for better tracing. This PR proposes to add the `log` crate and introduce logging level. This will change the output format with a logging level prefix like `[INFO]`.
> log: Introduce log crate

- src/fdt.rs
It is possible for the device tree to have multiple memory nodes. Iterate through all regions defined by all memory nodes.
> fdt: enumerate all memory nodes present

- .github/workflows/tests.yaml
> github: Disable ARM64 tests as runner is unavailable

- .github/workflows/tests.yaml
This commit partially reverts c68544c3face22d4f2f40761a2b85835fa9f8f0d
with modifications for worker changes.
> github: Re-enable ARM64 tests using new runner

- src/arch/aarch64/layout.rs
Bumping the possible page table range for aarch64 from 128G to 2TB to support larger systems. Without this increase we can't virtualize system memory beyond 128G for ARM CPUs.
Fixes #298
> aarch64/layout: Increase aarch64 system memory layout to 2TB.
